query ($id: UUID!) {
  result: examResultById(id: $id) {
    __typename
    ...ExamResult
  }
}

fragment ExamResult on ExamResultGQLModel {
  id
  lastchange
  exam
  {
    name
  }
  score
  examId
  studentAdmissionId
  studentAdmission
  {
    id
  }
}