query ReadStudentAdmission($id: UUID!) {
  result: studentadmissionById(id: $id) {
    __typename
    ...studentAdmission
  }
}

fragment studentAdmission on StudentAdmissionGQLModel {
  id
  lastchange
  admissionId
  userId
  stateId
  extendedConditionDate
  admissioned
  enrollmentDate
  admission
  {
    id
    name
  }
  exams
  {
    id
    name
  }
  examResults
  {
    exam
    {
      name
    }
    score
  }
  
}