query{
  result: examTypePage{
    __typename
    ...ExamType
  }
}

fragment ExamType on ExamTypeGQLModel{
  lastchange
  id
  masterExamTypeId
  name
  nameEn
  minScore
  maxScore
  admissionId
  created
  createdbyId
  createdby{
    id
  }
  changedbyId
  changedby{
    id
  }
  rbacobjectId
  rbacobject{
    id
  }
}