query ReadExamType($id: UUID!) {
  result: examTypeById(id: $id) {
    __typename
    ...ExamType
  }
}

fragment ExamType on ExamTypeGQLModel{
  lastchange
  id
  masterExamTypeId
  name
  nameEn
  minScore
  maxScore
  admissionId
  created
  createdbyId
  createdby{
    id
  }
  changedbyId
  changedby{
    id
  }
  rbacobjectId
  rbacobject{
    id
  }
}